### ISSUE TITLE
getChannel for BaseAmqp

### ISSUE THREAD

**Issue by hefekranz** [videlalvaro/Thumper#37]
and another suggestion.
The channel used is created in the BaseAmqp Class, but there is no way of getting it. Sure you could maybe do something like end($connection->channels), but that seems like a nasty solution and might even get you in trouble.
Getting the current channel is necessary since the spawned channels are only closed on disconnect.
If you have a long running process they will keep spamming and stay on the server without consumers.

**Comment by andrefigueira** [comment]
@hefekranz I got around this by extending `Thumper\Consumer` since channels is protected, if you extended it, you could just have:

```
public function getChannel()
{
    return $this->channel;
}
```

In your implementation, also allows you to implement many other features which currently aren't possible with this library, by extending this library, I've now been able to add functionality like multiple routing key binding, dead lettering, retry, and control of the consumer tag too.

**Comment by hefekranz** [comment]
well, obviously the best way to go. Thanks for the advice, missed that somehow.
